### ISSUE TITLE
Header bar menu really slow to open

### ISSUE THREAD

**Issue by dflock** [weclaw1/image-roll#35] opened 2022-01-03 16:33 UTC
When I click on the "hamburger" menu in the header bar, it reacts very slowly. There's a noticeable delay before the menu button highlights itself, then another noticeable delay before the menu appears, before hovering highlights items, etc... Same when it hides itself.

It's like there's a ~250ms delay before every interaction? Not sure if this is intentional or not, but the delay seems to get longer when you have an image open. Here's a recording:

https://user-images.githubusercontent.com/47756/147955421-d29c940c-6a21-4f2a-9585-3b4a9821cd38.mp4

**Comment by weclaw1** [comment] 2022-02-12 02:10
Could you check if the latest version (1.5.0) still has a delay? I remember that there was a slight delay in the previous versions but I cannot reproduce it in the latest. I made a pretty big refactor in 1.5.0 so that might have fixed this.

**Comment by dflock** [comment] 2022-02-12 05:15
Still the same for me with 1.5.0

**Comment by weclaw1** [comment] 2022-02-19 14:18
I will have be upgrading the project to GTK4 in a couple of months.
I will either rewrite it in relm4 (https://github.com/AaronErhardt/relm4) or recreate only the UI in Cambalache.
So this should be fixed after that upgrade.

**Comment by Pentaphon** [comment] 2022-05-30 22:06
Everything is really slow to use when opening up a high res image. Moving the windows, opening a menu, cropping, etc. It's like this image viewer has a built-in delay to it.

**Comment by weclaw1** [comment] 2022-05-31 22:03
Today I have started work on migrating to GTK4, so hopefully this will be fixed soon.
Sorry for inactivity lately, I was preoccupied with other things.

**Comment by weclaw1** [comment] 2022-07-05 23:54
Should be fixed in the new version. Please update to 2.0.0 and create a new issue if the problem still exists.

**Closed by weclaw1** 2022-07-05 23:54 UTC
